template: "product.floor-wipes-fresh-home.json"
description: "Template for the product.floor-wipes-fresh-home page, featuring sections: main-product, media-with-text, video, apps, related-products, faq, testimonials, apps."
sections:
  - "main (main-product)"
  - "c4a43766-4a19-4d00-9898-bcd0d58a97ac (media-with-text)"
  - "5713877b-7f32-4b02-9506-0d4105301c00 (video)"
  - "1688642188a9c7bb7d (apps)"
  - "2cc557d9-4240-49af-87a6-619ffb9c14fe (related-products)"
  - "beeafe09-2cb1-4ed4-9a41-c04f9f65c5d4 (faq)"
  - "4dd2b973-8a00-4f25-9139-08a7467cbda6 (testimonials)"
  - "1688645804e1409c6c (apps)"
